module.exports = {
    user: {
        '7тв': '7tv',
        'пинг': 'ping',
        'э': 'eh',
        'тг': 'tg',
        'правила': 'rules',
        'rules': 'rules',
        'iq': 'iq',
        'айкью': 'iq',
        'icq': 'iq',
        'игра': 'game',
        'followage': 'followage',
        'отслеживание': 'followage',
        'подписка': 'followage',
        'подписька': 'followage',
        'фоллоу': 'followage',
        'чебыло': 'categories',
        '+подарок': 'addgift',
        'подарок': 'gift',
        'тест': 'test',
        'команды': 'commands',
    },
    mod: {
        'варн': 'warn',
        'timeout': 'timeout',
        'бан': 'ban',
        'ban': 'ban',
    },
};