module.exports = {
    user: {
        '7тв': '7tv',
        'пинг': 'ping',
        'э': 'eh',
        'тг': 'tg',
        'правила': 'rules',
        'rules': 'rules',
        'iq': 'iq',
        'айкью': 'iq',
        'icq': 'iq',
        'игра': 'game',
        'followage': 'followage',
        'отслеживание': 'followage',
        'подписка': 'followage',
        'подписька': 'followage',
        'фоллоу': 'followage',
        'чебыло': 'categories',
        '+подарок': 'addgift',
        'подарок': 'gift',
        'тест': 'test',
        'команды': 'commands',
        'предложение': 'propose',
        'голос': 'vote',
        'итоги': 'stats',
        'пословица': 'proverb',
        'рулетка': 'roulette',
        'баллы': 'points',
        'очки': 'points',
<<<<<<< HEAD
        'сбросить_подарки': 'resetgift',
        'сброс_подарков': 'resetgift',
        '+очки': 'addpoints',
=======
        '-подарки': 'resetgift',
        '0подарки': 'resetgift',
>>>>>>> da2e31c741f414d5cf84f1e811131bbbe9b750d8
    },
    mod: {
        'варн': 'warn',
        'timeout': 'timeout',
        'бан': 'ban',
        'ban': 'ban',
    },
};